# Remove default files generated by install
rm ~/.zshrc
rm ~/.zshenv
rm ~/.gitconfig
rm ~/.p10k.zsh

ln -s ~/.dotfiles/.zshrc ~/.zshrc
ln -s ~/.dotfiles/.zshenv ~/.zshenv
ln -s ~/.dotfiles/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/.p10k.zsh ~/.p10k.zsh