# Remove default files generated by install
rm ~/.gitconfig
rm -r ~/.config/fish


ln -s ~/.dotfiles/.gitconfig ~/.gitconfig
ln -s ~/.dotfiles/.gitignore ~/.gitignore
ln -s ~/.dotfiles/fish ~/.config/fish