# Remove default files generated by install
_SCRIPT_DIR="$(CDPATH= cd "$(dirname "$0")" && pwd)"
. "$_SCRIPT_DIR/agentic-env/setup_helpers.sh"

run_cmd "rm ~/.gitconfig"
run_cmd "rm -r ~/.config/fish"

run_cmd "ln -s ~/.dotfiles/.gitconfig ~/.gitconfig"
run_cmd "ln -s ~/.dotfiles/.gitignore ~/.gitignore"
run_cmd "ln -s ~/.dotfiles/fish ~/.config/fish"

if command -v fish >/dev/null 2>&1 && command -v curl >/dev/null 2>&1; then
  run_cmd "fish --no-config -c 'if test -f ~/.config/fish/functions/fisher.fish; source ~/.config/fish/functions/fisher.fish; else; curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source; fisher install jorgebucaran/fisher; end; fisher update'"
else
  echo "Skipping Fish plugins: fish or curl missing"
fi

echo "setup_sym_links_cachyos complete"
